services:
  redis:
    image: redis:8-alpine
    container_name: redis_dev
    volumes:
      - redis_dev:/data/redis
    healthcheck:
      test: ["CMD-SHELL", "[ $(redis-cli ping) = 'PONG' ] || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped
  postgres:
    image: postgres:18
    container_name: postgres_dev
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - postgres_dev:/data/postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped
  client:
    container_name: client-dev
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "${FRONTEND_PORT}:5173"
    volumes:
      - ./client:/app
      - client_node_modules:/app/node_modules
    depends_on:
      server:
        condition: service_started
    restart: unless-stopped
  server:
    container_name: server-dev
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    command: sh -c "npm run prisma:push && npm run prisma:generate && npm run start:dev"
    environment:
      NODE_ENV: development
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public"
      REDIS_URL: "redis://redis:6379"
      CACHE_TTL: ${CACHE_TTL}
      PORT: 4200
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "4200:4200"
    volumes:
      - ./server:/app
      - server_node_modules:/app/node_modules
    restart: unless-stopped

volumes:
  redis_dev:
  postgres_dev:
  server_node_modules:
  client_node_modules:
