export const languageMap = {
  plain: "Plain text",
  markdown: "Markdown",
  javascript: "JavaScript",
  typescript: "TypeScript",
  jsx: "JSX",
  tsx: "TSX",
  markup: "HTML / XML",
  css: "CSS",
  scss: "SCSS",
  sass: "Sass",
  less: "Less",
  json: "JSON",
  yaml: "YAML",
  toml: "TOML",
  ini: "INI",
  bash: "Bash",
  "shell-session": "Shell Session",
  powershell: "PowerShell",
  batch: "Batch",
  python: "Python",
  java: "Java",
  c: "C",
  cpp: "C++",
  csharp: "C#",
  go: "Go",
  rust: "Rust",
  php: "PHP",
  ruby: "Ruby",
  kotlin: "Kotlin",
  swift: "Swift",
  dart: "Dart",
  sql: "SQL",
  graphql: "GraphQL",
  docker: "Docker",
  nginx: "Nginx",
  git: "Git",
  diff: "Diff",
  regex: "Regex",
  lua: "Lua",
  r: "R",
} as const;

export type Language = keyof typeof languageMap;
export type LanguageLabel = (typeof languageMap)[Language];