export const languageList = [
  { label: "Plain text", value: "plain" },
  { label: "Markdown", value: "markdown" },
  { label: "JavaScript", value: "javascript" },
  { label: "TypeScript", value: "typescript" },
  { label: "JSX", value: "jsx" },
  { label: "TSX", value: "tsx" },
  { label: "HTML / XML", value: "markup" },
  { label: "CSS", value: "css" },
  { label: "SCSS", value: "scss" },
  { label: "Sass", value: "sass" },
  { label: "Less", value: "less" },
  { label: "JSON", value: "json" },
  { label: "YAML", value: "yaml" },
  { label: "TOML", value: "toml" },
  { label: "INI", value: "ini" },
  { label: "Bash", value: "bash" },
  { label: "Shell Session", value: "shell-session" },
  { label: "PowerShell", value: "powershell" },
  { label: "Batch", value: "batch" },
  { label: "Python", value: "python" },
  { label: "Java", value: "java" },
  { label: "C", value: "c" },
  { label: "C++", value: "cpp" },
  { label: "C#", value: "csharp" },
  { label: "Go", value: "go" },
  { label: "Rust", value: "rust" },
  { label: "PHP", value: "php" },
  { label: "Ruby", value: "ruby" },
  { label: "Kotlin", value: "kotlin" },
  { label: "Swift", value: "swift" },
  { label: "Dart", value: "dart" },
  { label: "SQL", value: "sql" },
  { label: "GraphQL", value: "graphql" },
  { label: "Docker", value: "docker" },
  { label: "Nginx", value: "nginx" },
  { label: "Git", value: "git" },
  { label: "Diff", value: "diff" },
  { label: "Regex", value: "regex" },
  { label: "Lua", value: "lua" },
  { label: "R", value: "r" },
];

export const expirationList = [
  { label: "Never", value: "never" },
  { label: "Burn after read", value: "burn" },
  { label: "10 Minutes", value: "10m" },
  { label: "1 Hour", value: "1h" },
  { label: "1 Day", value: "1d" },
  { label: "3 Days", value: "3d" },
  { label: "1 Week", value: "1w" },
  { label: "2 Weeks", value: "2w" },
  { label: "1 Month", value: "1m" },
  { label: "6 Months", value: "6m" },
  { label: "1 Year", value: "1y" },
];

export const categoryList = [
  { label: "None", value: "none" },
  { label: "Programming", value: "programming" },
  { label: "Gaming", value: "gaming" },
  { label: "Art", value: "art" },
  { label: "Music", value: "music" },
  { label: "Science", value: "science" },
  { label: "Math", value: "math" },
  { label: "History", value: "history" },
];

export const exposureList = [
  { label: "Public", value: "public" },
  { label: "Unlisted", value: "unlisted" },
  { label: "Private", value: "private" },
  { label: "Protected", value: "protected" },
  { label: "Shared", value: "shared" },
];
